version: '3.8'

services:

  db:
    image: mysql
    container_name: mysql-vollmed-spring
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: vollmed-api
    restart: "no"
    volumes:
      - "./docker:/home"
    working_dir: /home